server:
  port: 8088
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf-8
      username: root
      password: shangyi
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img\
cache:
  redis:
    time-to-live: 1800000 #设置缓存数据过期时间
aliyun:
  sms:
    sms-access-key-id: LTAI5t6yJtNVMhuGHn2Kk692
    sms-access-key-secret: nxYexxUO9kjPrPJK4ujChBZLMDkZbH
    sms-endpoint: dysmsapi.aliyuncs.com
    sms-template-code: SMS_154950909
    sms-sign-name: 阿里云短信测试
